# Start Docker: docker-compose up

version: '3.7'
services:

  # link to access: http://localhost:8500/ui/dc1/services
  consul:
    image: consul:1.6.1
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -ui --config-dir /etc/consul.d/server
    ports:
      - target: 8300
        published: 8300
        mode: host
      - target: 8400
        published: 8400
        mode: host
      - target: 8500
        published: 8500
        mode: host
      - target: 53
        published: 8600
        mode: host
    volumes:
      - ./server:/etc/consul.d/server
    networks:
      - local-ntk

  consul2:
    image: consul:1.6.1
    command: agent -server -retry-join=consul -bind 0.0.0.0 -client 0.0.0.0 --config-dir /etc/consul.d/agent
    volumes:
      - ./agent:/etc/consul.d/agent
    networks:
      - local-ntk

  consul3:
    image: consul:1.6.1
    command: agent -server -retry-join=consul -bind 0.0.0.0 -client 0.0.0.0 --config-dir /etc/consul.d/agent
    volumes:
      - ./agent:/etc/consul.d/agent
    networks:
      - local-ntk

networks:
  local-ntk:
    driver: bridge